// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package quotesdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Quote struct {
	ID            uuid.UUID          `json:"id"`
	QuoteNo       string             `json:"quote_no"`
	Status        string             `json:"status"`
	Title         string             `json:"title"`
	TotalAmount   int64              `json:"total_amount"`
	ClientCompany string             `json:"client_company"`
	SalesName     string             `json:"sales_name"`
	IssueDate     pgtype.Date        `json:"issue_date"`
	Body          []byte             `json:"body"`
	CreatedBy     string             `json:"created_by"`
	UpdatedBy     string             `json:"updated_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type QuoteSerial struct {
	DateKey string `json:"date_key"`
	NextSeq int32  `json:"next_seq"`
}
