// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package quotesdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countQuotes = `-- name: CountQuotes :one
SELECT COUNT(*)
FROM quotes
WHERE deleted_at IS NULL
  AND ($1::date  IS NULL OR issue_date >= $1::date)
  AND ($2::date    IS NULL OR issue_date <= $2::date)
  AND ($3::text IS NULL OR sales_name  = $3::text)
  AND ($4::text     IS NULL OR status      = $4::text)
`

type CountQuotesParams struct {
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
	SalesName *string     `json:"sales_name"`
	Status    *string     `json:"status"`
}

// 配 ListQuotes 用於 pagination total 欄位。filter 條件必須跟 ListQuotes 完全一致。
func (q *Queries) CountQuotes(ctx context.Context, arg CountQuotesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotes,
		arg.DateFrom,
		arg.DateTo,
		arg.SalesName,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (
  quote_no, status, title, total_amount,
  client_company, sales_name, issue_date,
  body, created_by, updated_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $9
)
RETURNING id, quote_no, created_at, updated_at
`

type CreateQuoteParams struct {
	QuoteNo       string      `json:"quote_no"`
	Status        string      `json:"status"`
	Title         string      `json:"title"`
	TotalAmount   int64       `json:"total_amount"`
	ClientCompany string      `json:"client_company"`
	SalesName     string      `json:"sales_name"`
	IssueDate     pgtype.Date `json:"issue_date"`
	Body          []byte      `json:"body"`
	CreatedBy     string      `json:"created_by"`
}

type CreateQuoteRow struct {
	ID        uuid.UUID          `json:"id"`
	QuoteNo   string             `json:"quote_no"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 建立新報價。issue_date 可為 NULL（前端有時還沒選日期就先 save draft）。
// created_by 跟 updated_by 都填同一個 email（建立 = 第一次修改）。
func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (CreateQuoteRow, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.QuoteNo,
		arg.Status,
		arg.Title,
		arg.TotalAmount,
		arg.ClientCompany,
		arg.SalesName,
		arg.IssueDate,
		arg.Body,
		arg.CreatedBy,
	)
	var i CreateQuoteRow
	err := row.Scan(
		&i.ID,
		&i.QuoteNo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const distinctSales = `-- name: DistinctSales :many
SELECT DISTINCT sales_name
FROM quotes
WHERE deleted_at IS NULL AND sales_name <> ''
ORDER BY sales_name
`

// 不重複業務名單（給前端歷史頁 filter dropdown 用）。
// 過濾空字串避免「未填業務」也算一個選項。
func (q *Queries) DistinctSales(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, distinctSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var sales_name string
		if err := rows.Scan(&sales_name); err != nil {
			return nil, err
		}
		items = append(items, sales_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuote = `-- name: GetQuote :one
SELECT id, quote_no, status, title, total_amount, client_company, sales_name, issue_date, body, created_by, updated_by, created_at, updated_at, deleted_at
FROM quotes
WHERE id = $1 AND deleted_at IS NULL
`

// 取單筆完整資料（含 body JSONB），軟刪除的視為不存在（pgx.ErrNoRows）。
func (q *Queries) GetQuote(ctx context.Context, id uuid.UUID) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.QuoteNo,
		&i.Status,
		&i.Title,
		&i.TotalAmount,
		&i.ClientCompany,
		&i.SalesName,
		&i.IssueDate,
		&i.Body,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQuoteByNo = `-- name: GetQuoteByNo :one
SELECT id, quote_no, status, title, total_amount, client_company, sales_name, issue_date, body, created_by, updated_by, created_at, updated_at, deleted_at
FROM quotes
WHERE quote_no = $1 AND deleted_at IS NULL
`

// 用報價單號取單筆完整資料，保留 #/quote/AW-... deep-link 書籤（業務 deep link）。
// quote_no 有 UNIQUE 約束，最多一筆；軟刪除的視為不存在（pgx.ErrNoRows）。
func (q *Queries) GetQuoteByNo(ctx context.Context, quoteNo string) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuoteByNo, quoteNo)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.QuoteNo,
		&i.Status,
		&i.Title,
		&i.TotalAmount,
		&i.ClientCompany,
		&i.SalesName,
		&i.IssueDate,
		&i.Body,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listQuotes = `-- name: ListQuotes :many
SELECT
  id, quote_no, status, title, total_amount,
  client_company, sales_name, issue_date, updated_at
FROM quotes
WHERE deleted_at IS NULL
  AND ($3::date  IS NULL OR issue_date >= $3::date)
  AND ($4::date    IS NULL OR issue_date <= $4::date)
  AND ($5::text IS NULL OR sales_name  = $5::text)
  AND ($6::text     IS NULL OR status      = $6::text)
-- Template 狀態置頂:業務把常用模板放在最上方,方便從歷史頁一鍵複製使用。
-- (status = 'template') 在 Postgres 產生 boolean,DESC 讓 TRUE 排在前面。
-- 非模板內部按 quote_no DESC — 用單號降冪 (AW-YYMMDD-NNN 字典序 = 日期
-- 降序),讓最新開的報價自然在最上。不用 updated_at 是為了避免業務改狀態
-- 或編輯內容就把該筆拉到最上面,PM 反映這樣不直覺 (2026-07)。
ORDER BY (status = 'template') DESC, quote_no DESC
LIMIT  $1
OFFSET $2
`

type ListQuotesParams struct {
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
	SalesName *string     `json:"sales_name"`
	Status    *string     `json:"status"`
}

type ListQuotesRow struct {
	ID            uuid.UUID          `json:"id"`
	QuoteNo       string             `json:"quote_no"`
	Status        string             `json:"status"`
	Title         string             `json:"title"`
	TotalAmount   int64              `json:"total_amount"`
	ClientCompany string             `json:"client_company"`
	SalesName     string             `json:"sales_name"`
	IssueDate     pgtype.Date        `json:"issue_date"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// 列表（依 spec §3.4：updated_at DESC、軟刪除不返回、metadata only 不含 body）。
// Filter 用 nullable params：傳 NULL 表示不過濾該欄位。
func (q *Queries) ListQuotes(ctx context.Context, arg ListQuotesParams) ([]ListQuotesRow, error) {
	rows, err := q.db.Query(ctx, listQuotes,
		arg.Limit,
		arg.Offset,
		arg.DateFrom,
		arg.DateTo,
		arg.SalesName,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotesRow{}
	for rows.Next() {
		var i ListQuotesRow
		if err := rows.Scan(
			&i.ID,
			&i.QuoteNo,
			&i.Status,
			&i.Title,
			&i.TotalAmount,
			&i.ClientCompany,
			&i.SalesName,
			&i.IssueDate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextNumber = `-- name: NextNumber :one

INSERT INTO quote_serials (date_key, next_seq)
VALUES ($1, 2)
ON CONFLICT (date_key) DO UPDATE
  SET next_seq = quote_serials.next_seq + 1
RETURNING next_seq - 1 AS issued_seq
`

// Quote-app SQL queries（sqlc input）
// 每個 query 用 `-- name: XxxQuery :one/many/exec` 註解標記、sqlc 會生對應 Go 函式
//
// 設計原則：
// · NextNumber 用 PostgreSQL atomic INSERT...ON CONFLICT...RETURNING（不需 lock）
// · 所有查詢都過濾 deleted_at IS NULL（軟刪除不可見）
// · ListQuotes 用 nullable params 實現可選 filter（NULL = 不過濾該欄）
// 配發下一個流水號 (atomic, race-free)。回上一個 next_seq 即「剛配發的值」。
// 例：date_key='260515', 連跑 3 次回 1, 2, 3。
func (q *Queries) NextNumber(ctx context.Context, dateKey string) (int32, error) {
	row := q.db.QueryRow(ctx, nextNumber, dateKey)
	var issued_seq int32
	err := row.Scan(&issued_seq)
	return issued_seq, err
}

const softDeleteQuote = `-- name: SoftDeleteQuote :execrows
UPDATE quotes
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// 軟刪除（標記 deleted_at = now()）。:execrows 回 affected rows，handler 用來
// 區分「刪除成功」與「找不到 / 已被刪過」(回 0 rows → 404)。
func (q *Queries) SoftDeleteQuote(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteQuote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateQuote = `-- name: UpdateQuote :one
UPDATE quotes SET
  status         = $2,
  title          = $3,
  total_amount   = $4,
  client_company = $5,
  sales_name     = $6,
  issue_date     = $7,
  body           = $8,
  updated_by     = $9,
  updated_at     = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, quote_no, updated_at
`

type UpdateQuoteParams struct {
	ID            uuid.UUID   `json:"id"`
	Status        string      `json:"status"`
	Title         string      `json:"title"`
	TotalAmount   int64       `json:"total_amount"`
	ClientCompany string      `json:"client_company"`
	SalesName     string      `json:"sales_name"`
	IssueDate     pgtype.Date `json:"issue_date"`
	Body          []byte      `json:"body"`
	UpdatedBy     string      `json:"updated_by"`
}

type UpdateQuoteRow struct {
	ID        uuid.UUID          `json:"id"`
	QuoteNo   string             `json:"quote_no"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 更新報價（依 spec §3.3：忽略 body 內 quote_no，後端不改該欄）。
// updated_at 自動 now()。回 :one 而非 :exec 以驗證該筆未被軟刪除（找不到 = err）。
func (q *Queries) UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (UpdateQuoteRow, error) {
	row := q.db.QueryRow(ctx, updateQuote,
		arg.ID,
		arg.Status,
		arg.Title,
		arg.TotalAmount,
		arg.ClientCompany,
		arg.SalesName,
		arg.IssueDate,
		arg.Body,
		arg.UpdatedBy,
	)
	var i UpdateQuoteRow
	err := row.Scan(&i.ID, &i.QuoteNo, &i.UpdatedAt)
	return i, err
}
