// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package quotesdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// 配 ListQuotes 用於 pagination total 欄位。filter 條件必須跟 ListQuotes 完全一致。
	CountQuotes(ctx context.Context, arg CountQuotesParams) (int64, error)
	// 建立新報價。issue_date 可為 NULL（前端有時還沒選日期就先 save draft）。
	// created_by 跟 updated_by 都填同一個 email（建立 = 第一次修改）。
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (CreateQuoteRow, error)
	// 不重複業務名單（給前端歷史頁 filter dropdown 用）。
	// 過濾空字串避免「未填業務」也算一個選項。
	DistinctSales(ctx context.Context) ([]string, error)
	// 取單筆完整資料（含 body JSONB），軟刪除的視為不存在（pgx.ErrNoRows）。
	GetQuote(ctx context.Context, id uuid.UUID) (Quote, error)
	// 列表（依 spec §3.4：updated_at DESC、軟刪除不返回、metadata only 不含 body）。
	// Filter 用 nullable params：傳 NULL 表示不過濾該欄位。
	ListQuotes(ctx context.Context, arg ListQuotesParams) ([]ListQuotesRow, error)
	// Quote-app SQL queries（sqlc input）
	// 每個 query 用 `-- name: XxxQuery :one/many/exec` 註解標記、sqlc 會生對應 Go 函式
	//
	// 設計原則：
	// · NextNumber 用 PostgreSQL atomic INSERT...ON CONFLICT...RETURNING（不需 lock）
	// · 所有查詢都過濾 deleted_at IS NULL（軟刪除不可見）
	// · ListQuotes 用 nullable params 實現可選 filter（NULL = 不過濾該欄）
	// 配發下一個流水號 (atomic, race-free)。回上一個 next_seq 即「剛配發的值」。
	// 例：date_key='260515', 連跑 3 次回 1, 2, 3。
	NextNumber(ctx context.Context, dateKey string) (int32, error)
	// 軟刪除（標記 deleted_at = now()）。:execrows 回 affected rows，handler 用來
	// 區分「刪除成功」與「找不到 / 已被刪過」(回 0 rows → 404)。
	SoftDeleteQuote(ctx context.Context, id uuid.UUID) (int64, error)
	// 更新報價（依 spec §3.3：忽略 body 內 quote_no，後端不改該欄）。
	// updated_at 自動 now()。回 :one 而非 :exec 以驗證該筆未被軟刪除（找不到 = err）。
	UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (UpdateQuoteRow, error)
}

var _ Querier = (*Queries)(nil)
