// BPField — Builder-panel form field (label + input).
//
// Legacy CSS: `.bp-field` (vertical, label-on-top) and
// `.bp-section-compact .bp-field` (horizontal, fixed 80px label on left).
// We expose the layout switch as a `compact` prop instead of relying on a
// parent class, because CSS Modules locally scope class names and
// parent-selector inheritance doesn't cross module boundaries.
//
// All standard <input> attributes (placeholder / readOnly / type / etc) pass
// through via spread.

import { useId, type InputHTMLAttributes, type JSX } from 'react';

import styles from './BPField.module.scss';

interface BPFieldProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'id'> {
  label: string;
  /** Horizontal layout (label left, input right). Default false → label-on-top. */
  compact?: boolean;
  /** Optional id (auto-generated by useId if omitted — supports a11y). */
  id?: string;
}

export function BPField({
  label,
  compact = false,
  id,
  className,
  ...inputProps
}: BPFieldProps): JSX.Element {
  const autoId = useId();
  const fieldId = id ?? autoId;
  const rootClass = [styles.field, compact && styles.compact, className].filter(Boolean).join(' ');

  return (
    <div className={rootClass}>
      <label htmlFor={fieldId}>{label}</label>
      <input {...inputProps} id={fieldId} />
    </div>
  );
}
